# Generated by Django 4.1 on 2022-08-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='current_job',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
