# Generated by Django 4.1 on 2022-08-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_job_current_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_shortname',
            field=models.CharField(default='uniquename', max_length=20),
            preserve_default=False,
        ),
    ]
