# Generated by Django 4.1 on 2022-08-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_project_shortname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_shortname',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
