# Generated by Django 4.1 on 2022-09-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_job_projects_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='display_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
